### PR TITLE
Unknown var fix

### PR DESCRIPTION
**Pull request by jasalisbury**

### CODE REVIEW

**Review by maddy-jo — APPROVED** [review]

**Review by kalilsn — APPROVED** [review]

**Comment by maddy-jo** [comment]
@jasalisbury out of curiosity, why wasn't it possible to assign `config` back to itself? also, that function does clean the config in place, so not necessary to create the new variable

EDIT: nvm i see what was happening

**Comment by kalilsn** [comment]
@mjlumetta I think the problem is that `updatedConfig` is referenced in the next line, and I'd removed the declaration of that variable entirely.

**Comment by maddy-jo** [comment]
that `isEquals` check has always been and continues to be useless

**Comment by kalilsn** [comment]
🙃 yeah if it modifies the original object then this code doesn't really make any sense.

**Comment by maddy-jo** [comment]
nope... and before that, the `host` from `updateRouteIds` was preventing the other possibility. should we change this check to assert that the returned config matches the expected config, since we shouldn't need to write updates back to the file? in which case, the cleaning is still helpful but it should be set to updatedConfig earlier? or what is `state` in this function?

**Comment by jasalisbury** [comment]
> nope... and before that, the `host` from `updateRouteIds` was preventing the other possibility. should we change this check to assert that the returned config matches the expected config, since we shouldn't need to write updates back to the file? in which case, the cleaning is still helpful but it should be set to updatedConfig earlier? or what is `state` in this function?

I would think (hope) we can remove a lot of this code here since kongfig no longer updates the config file.

**Pull request merged**
