### PR TITLE
Add logger for acl plugins

### PR DESCRIPTION
**Pull request by jasalisbury**
Old output:
```
consumer adhoc is up to date
unknown action { type: 'noop-acl', noop: true, acl: { group: 'api-users' } }
```

New output:
```
consumer adhoc is up to date
- acl api-users is up to date
```

### CODE REVIEW

**Review by kalilsn — APPROVED** [review]
thanks for cleaning this up! can you increment the version too?

**Review by maddy-jo — APPROVED** [review]

**Comment by jasalisbury** [comment]
> thanks for cleaning this up! can you increment the version too?

All I need to do is update the version in `package.json`?

**Comment by kalilsn** [comment]
yeah! it's not that important for this change, but probably a good practice for us in general

**Comment by maddy-jo** [comment]
@jasalisbury you can run `npm version patch` as a utility for that

**Pull request merged**
