### PR TITLE
Add missing version param

### PR DESCRIPTION
**Pull request by kalilsn**
Not sure how I missed this before! I added a test case for these (including plugins on the route), but inadvertently wrote a test for the bug I wanted to demo in our standup today. I'm leaving that out for now because I still haven't figured out a solution. I'll open another PR with that test as the starting point.

### CODE REVIEW

**Review by jasalisbury — APPROVED** [review]
I've never been a fan of being able to call functions with fewer/more parameters in JS. I'm sure there is a reason it is allowed but I've only really seen it cause bugs.

**Review by maddy-jo — COMMENTED** [review]
reviewed and no objections but not approving bc i still want to understand Kongfig's internal logic better

**Comment by kalilsn** [comment]
Merging this now so that I'm not leaving kongfig in a worse state than it was in when I started. I'll still do my best to answer any questions you have @mjlumetta!

**Comment by maddy-jo** [comment]
@kalilsn no you're good!! more so saying that it's a big application, and so i only have a vague and pre-refactor knowledge of the architecture. more like i'll try to play around with it at some point in the future :)

**Pull request merged**
